### ISSUE TITLE
vcl_config_manual.h not found

### ISSUE THREAD

**Issue by rfabbri** [vxl/vxl#311]
Hi,

I'm building another library that depends on VXL using CMAKE,
and with the simplest code I get this compile error:

```
In file included from /Users/rfabbri/cprg/vxlprg/vxl/vcl/vcl_vector.h:5:
/Users/rfabbri/cprg/vxlprg/vxl/vcl/vcl_compiler.h:121:10: fatal error: 'vcl_config_manual.h' file not found
#include <vcl_config_manual.h>
```

I did not do a make install in VXL but rather pointed to the vxl binary folder in my lib's CMAKE.

Any ideas?

**Comment by mleotta** [comment]
I had this issue recently as well.  vcl_config_manual.h is in the build directory.  There are new CMake variables that include both the source and build include directories.  The names are the same as before but with an “S".  So you need to update your “include_directories” call to use  ${VXL_CORE_INCLUDE_DIRS}  instead of ${VXL_CORE_INCLUDE_DIR}.  The same is true for  ${VXL_VCL_INCLUDE_DIRS}.

—Matt

**Comment by rfabbri** [comment]
Including VXL_VCL_INCLUDE_DIRS works. Thanks!
